version: '3'
services:
  backend:
    container_name: bowling-backend
    image: "bowling-backend:latest"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1 # helps with python logging, remember and forget this often
    networks:
      - docker
    volumes:
      - ../backend:/code
    working_dir: /code
    entrypoint: ${BACKEND_ENTRYPOINT}
    ports:
      - 5000:5000
  db:
    container_name: bowling-db
    image: "mongo:3-stretch"
    networks:
      - docker
networks:
  docker: